{% set name = "autogluon.features" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd
  # Use the latest commit temporarily
  url: https://github.com/autogluon/autogluon/archive/e6458bdbbaa22908457a199f1095b80edc3b85f9.tar.gz
  sha256: 39e542cfc5f7d5ba767dbb20fa462d9a7d535115011b3cd2e98dd70175090722

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./features -vv
  number: 0
  script_env:
   - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  # see https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >=3.8,<3.11
    - numpy >=1.21,<1.27
    - pandas >=1.4.1,<1.6
    - scikit-learn >=1.0,<1.3
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.features
  commands:
    - python -c "from autogluon.features import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.features/
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
